DROP TRIGGER IF EXISTS trg_episode_catalog_entries_series ON public.media_items;
DROP TRIGGER IF EXISTS trg_episode_catalog_entries_episodes ON public.episodes;
DROP TRIGGER IF EXISTS trg_episode_catalog_entries_media_files ON public.media_files;
DROP TRIGGER IF EXISTS trg_episode_catalog_entries_episode_libraries ON public.episode_libraries;

DROP FUNCTION IF EXISTS public.episode_catalog_entries_series_trigger();
DROP FUNCTION IF EXISTS public.episode_catalog_entries_episodes_trigger();
DROP FUNCTION IF EXISTS public.episode_catalog_entries_media_files_trigger();
DROP FUNCTION IF EXISTS public.episode_catalog_entries_episode_libraries_trigger();
DROP FUNCTION IF EXISTS public.refresh_episode_catalog_entries_for_series(text);
DROP FUNCTION IF EXISTS public.refresh_episode_catalog_entries_for_episode(text);
DROP FUNCTION IF EXISTS public.refresh_episode_catalog_entry(text, integer);
DROP FUNCTION IF EXISTS public.episode_catalog_resolution_rank(text);
DROP FUNCTION IF EXISTS public.episode_catalog_normalized_resolution(text);
DROP FUNCTION IF EXISTS public.episode_catalog_rating_rank(text);

DROP INDEX IF EXISTS public.idx_episode_catalog_entries_subtitle_gin;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_audio_gin;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_resolution_codes_gin;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_countries_gin;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_networks_gin;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_studios_gin;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_genres_gin;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_non_dolby_vision;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_dolby_vision;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_non_hdr;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_hdr;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_status;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_bitrate;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_resolution;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_tmdb;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_imdb;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_runtime;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_content_rating;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_year;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_air_date;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_added;
DROP INDEX IF EXISTS public.idx_episode_catalog_entries_title;

DROP TABLE IF EXISTS public.episode_catalog_entries;
